server:
  port: 8080
app:
  client-list-page:
    msg: Коля любит Мамбу!!!
    msg2: ${app.client-list-page.msg} И Сережа тоже!

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springmvc?serverTimezone=Europe/Moscow
    username: root
    password: sasha
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop